### ISSUE TITLE
Why use your own package registry pkgreg.com?

### ISSUE THREAD

**Issue by pjlammertyn** [muonw/mascara#1]
Why not use npm?
Your own registry doesn't have the security measures that npm has.
And it makes me suspicious that it holds some malicious code.
As this security analysis points out: https://snyk.io/test/website-scanner/?test=230213_AiDcCV_4Z8&utm_medium=referral&utm_source=webpagetest&utm_campaign=website-scanner

**Comment by muonw-public** [comment]
Thank you for sharing your concerns. You have every right to be wary of other's codes, especially when they deviate from the norms.

The short answer to "Why not use npm?" is that the npm public registry ([registry.npmjs.org](https://registry.npmjs.org)) is limiting.

- The source code of npm public registry is not publicly available. As a result, it's unclear [to muonw] whether the code is still being maintained and up to standard. It's certainly in everyone's best interest if npm public registry is well maintained.

- The npm public registry does not offer an option to implement new features or customization.  

- The ToS of npm's closed-source public registry (named "[npm Open-Source Terms](https://docs.npmjs.com/policies/open-source-terms)") does not meet the requirements of muonw. With regard to security, "npm makes no warranty that npm Services will [...] operate in a [...] secure [...] manner."

> Use of npm Services is at your sole risk. npm Services are provided on an "as is" and "as available" basis. npm expressly disclaims all warranties of any kind, whether express, implied, or statutory, including implied warranties of title, noninfringement, merchantability, and fitness for a particular purpose.
> 
> npm makes no warranty that npm Services will meet your requirements, operate in an uninterrupted, timely, secure, or error-free manner, or that errors in npm Services will be corrected.
> 
> You receive material via npm Services at your sole risk. You will be solely responsible for any damage to your computer system and network, as well as any data loss that may result from use of npm Services or material received via npm Services.

If you have audited the code but just don't trust the package, you have the option to clone the repository and package it yourself (e.g. `npm run package`). It may not be as convenient as downloading it from [node.pkgreg.com](https://node.pkgreg.com), but obviates the need to trust anyone.

**Comment by pjlammertyn** [comment]
Your arguments make little sense.

- The npm package manager is open source. The package hosting platform https://registry.npmjs.org/ is not. The same goes for git: git CLI is open source, GitHub is not. If you are consistently, you should also leave Github!

- What new features or customizations do you mean? Give some examples. And how will you integrate those new features of your custom very open registry, into the package manager CLI?

- Behind npmjs there is a firm (Microsoft) that wants legal coverage. They don't want to be held responsible for the contents of the packages that they are hosting, uptime guarantees, etc... Which make sense. So therefore I presume that you are willing to bear the responability of bug free, secure and always uptime hosting of your packages? With the possibility to get sued, if you fail to deliver these guarantees?

**Comment by muonw-public** [comment]
There are always decisions that seem incorrect to some and I understand one's desire to make sense of them. There are good answers to these questions, and there are more questions that you will have to answer before we get on the same page. I'll leave the research to the unconvinced readers, since this thread is transitioning from the original security concern to the comparison of registries.
